name : superunko
cmdname : superunko
summary : Super Unko
description : super_unko project is the one of the awesome, clean and sophisticated OSS project in the world. Let us create shit commands.
version : 1.0.0
changelog : New feature
url : https://github.com/greymd/super_unko
author : Awesome Unkontributors
email : super@unko.com
