language: generic

addons:
  apt:
    packages:
      - figlet
      - toilet
      - gcc
      - make
      - golang
      - shellcheck

install:
  - GO111MODULE=off go get mvdan.cc/sh/cmd/shfmt

script:
  - ls -1 bin/* | grep -v unko.puzzle | xargs shfmt -i 2 -ci -sr -d
  - ls -1 bin/* | grep -v unko.puzzle | xargs shellcheck
  - ./test.sh
