version: '3'

services:
  super_unko:
    build:
      context: ./
      dockerfile: ./build/super_unko/Dockerfile
    image: unkontributors/super_unko

  formatter:
    image: peterdavehello/shfmt
    container_name: formatter
    entrypoint:
      - "shfmt"
      - "--version"

  linter:
    image: koalaman/shellcheck
    container_name: linter
    entrypoint:
      - "shellcheck"
      - "--version"
